name: Waka Readme

on:
  schedule:
    - cron: '* * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: laptop
    steps:
      - uses: thegostisdead/thegostisdead@master
        with:
          branch: develop
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
